name: Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.1.0 # v2
    - uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v2
      with:
        version: v1.41.1
      continue-on-error: true # temporary
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.1.0 # v2
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2
      with:
        go-version: '1.16.5'
    - run: go build -v ./...
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.1.0 # v2
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2
      with:
        go-version: '1.16.5'
    - run: go test -v ./...
    - run: go vet ./...
